FROM ubuntu:wily

RUN ( apt-get update ; \
    apt-get upgrade -y ; \
    add-apt-repository ppa:gluster/glusterfs-3.7 ;\
    apt-get -y install glusterfs-server glusterfs-client ;\
    apt-get -y install xfsprogs ;\
    apt-get -y install lvm2 ;\
    apt-get -y install supervisor ;\
    apt-get -y clean all ; \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*; \
    )

ADD FILES.gluster /
